using System.Collections.Generic;
using Yueby.Utils;

namespace Yueby.AvatarTools.ClothesManager
{
    public class CMLocalization : Localization
    {
        public CMLocalization()
        {
            Languages = new Dictionary<string, Dictionary<string, string>>
            {
                {
                    "中文", new Dictionary<string, string>
                    {
                        { "window_title", "服装管理" },
                        { "category", "分类" },
                        { "clothes", "服装" },
                        { "category_name", "分类名" },
                        { "clothes_name", "衣服名" },
                        { "new_category_name", "新类型" },
                        { "driver_is_local", "是否本地触发" },
                        { "clothes_configure", "配置" },
                        { "clothes_configure_none_clothes", "无选中衣服" },
                        { "clothes_preview", "预览" },
                        { "clothes_set_to_default", "设为默认" },
                        { "clothes_already_default", "已为默认" },
                        { "clothes_select_tip", "请选择或添加一个衣服配置。" },
                        { "parent_menu", "父菜单" },
                        { "parent_menu_tip", "如果父菜单为空的话，会将Avatar的默认菜单作为父菜单智能创建子菜单。" },
                        { "apply", "应用" },
                        { "open_backup_path", "打开备份路径" },
                        { "capture_start", "开始截图" },
                        { "capture", "截取" },
                        { "cancel", "取消" },
                        { "capture_tip_warning", "请将场景视图的\"Gizmos\"按钮打开以让截图工具正常工作！" },
                        { "capture_tip_info", "拖动场景视图可以调整截图内容！" },
                        { "capture_obj_camera", "服装管理_捕获相机" },
                        { "capture_obj_avatar", "服装管理_捕获模型_" },
                        { "tips", "提示" },
                        { "yes", "是" },
                        { "no", "否" },
                        { "tip_success_save", "保存成功，是否跳转查看？" },
                        { "show", "显示" },
                        { "hide", "隐藏" },
                        { "blend_shapes", "形态键" },
                        { "driver_is_using", "是否使用参数驱动" },
                        { "driver_enter", "进入时" },
                        { "driver_exit", "离开时" },
                        { "driver_select_tip", "请选择一个参数！" },
                        { "driver_dest_value", "值" },
                        { "driver_not_suit_warning", "{0}是{1}类型参数，不支持{2}操作!" },
                        { "driver_chance", "概率" },
                        { "driver_min_value", "最小值" },
                        { "driver_max_value", "最大值" },
                        { "driver_source", "源" },
                        { "driver_destination", "目标" },
                        { "driver_convert_range", "转换范围" },
                        { "driver_tip_not_allow_trigger", "源参数不可以是Trigger类型!" },
                        { "driver_tip_convert", "值将会从{0}类型转换为{1}类型。" },
                        { "tool_init_label", "初始设置" },
                        { "tool_init_avatar", "模型" },
                        { "tool_init_create_btn", "创建" },
                        { "tool_init_data", "数据" },
                        { "tool_init_hide_options", "配置隐藏" },
                        { "tool_init_none_data_tip", "未找到配置，点击按钮创建一个。" },
                        { "tool_init_tip_delete_warning", "你确定要删除该配置文件吗？删除后将不会得到撤回！" },
                        { "tool_init_delete_btn", "删除" },
                        { "warning", "警告" },
                        { "ok", "好的" },
                        { "apply_next_page", "下一个" },
                        { "in_playing_mode_tip", "当前为播放模式，编辑器不可用，请回到编辑模式在进行操作！" },
                        { "clothes_none_bs_tip", "{0}：无SkinnedMeshRenderer组件,自动排除！" },
                        { "clothes_all_bs_tip", "{0}上形态键已全部添加，无法再次添加新的形态键！" },
                        { "apply_menu_find_tip", "找到 “{0}” 菜单，是否将它作为工具用主菜单？这将会替换掉原来的内容！" },
                        { "apply_success_tip", "已成功应用！" },
                    }
                },
                {
                    "English", new Dictionary<string, string>
                    {
                        { "window_title", "Clothes Manager" },
                        { "category", "Category" },
                        { "clothes", "Clothes" },
                        { "category_name", "Category Name" },
                        { "clothes_name", "Clothes Name" },
                        { "new_category_name", "New Type" },
                        { "driver_is_local", "Is Local" },
                        { "clothes_configure", "Configure" },
                        { "clothes_configure_none_clothes", "None Selected" },
                        { "clothes_preview", "Preview" },
                        { "clothes_set_to_default", "Set Default" },
                        { "clothes_already_default", "Already Default" },
                        { "clothes_select_tip", "Please select one clothes." },
                        { "parent_menu", "Parent Menu" },
                        { "parent_menu_tip", "If parent menu is null, it will auto using avatar's default menu as parent menu." },
                        { "apply", "Apply" },
                        { "open_backup_path", "Open Backup Path" },
                        { "capture_start", "Start Capture" },
                        { "capture", "Capture" },
                        { "cancel", "Cancel" },
                        { "capture_tip_warning", "Please toggle on the \"Gizmos\" button in scene view so that capture feature will be work well!" },
                        { "capture_tip_info", "Drag scene view to adjust capture content!" },
                        { "capture_obj_camera", "ClothesManager_CaptureCamera" },
                        { "capture_obj_avatar", "ClothesManager_CaptureAvatar_" },
                        { "tips", "Tips" },
                        { "yes", "Yes" },
                        { "no", "No" },
                        { "tip_success_save", "Save success，jump to check?" },
                        { "show", "Show" },
                        { "hide", "Hide" },
                        { "blend_shapes", "BlendShapes" },
                        { "driver_is_using", "Using Parameter Driver" },
                        { "driver_enter", "When Enter" },
                        { "driver_exit", "When Exit" },
                        { "driver_select_tip", "Please select one parameter！" },
                        { "driver_dest_value", "Value" },
                        { "driver_not_suit_warning", "{1} parameters don't support the {2} type" },
                        { "driver_chance", "Chance" },
                        { "driver_min_value", "Min" },
                        { "driver_max_value", "Max" },
                        { "driver_source", "Source" },
                        { "driver_destination", "Dest" },
                        { "driver_convert_range", "Convert Range" },
                        { "driver_tip_not_allow_trigger", "Source parameter can't be the Trigger type!" },
                        { "driver_tip_convert", "Value will be converted from a {0} to a {1}." },
                        { "tool_init_label", "Init" },
                        { "tool_init_avatar", "Avatar" },
                        { "tool_init_create_btn", "Create" },
                        { "tool_init_data", "Data" },
                        { "tool_init_hide_options", "Configure Hide" },
                        { "tool_init_none_data_tip", "Couldn't find configure data, click button to create." },
                        { "tool_init_tip_delete_warning", "Are you sure to delete this configure data? It will not be restored after deletion." },
                        { "tool_init_delete_btn", "Delete" },
                        { "warning", "Warning" },
                        { "ok", "Ok" },
                        { "apply_next_page", "Next" },
                        { "in_playing_mode_tip", "Current in playing mode, editor will disable, please back to edit mode." },
                        { "clothes_none_bs_tip", "{0}:\n Could not found SkinnedMeshRenderer component, removed！" },
                        { "clothes_all_bs_tip", "All blendShapes on {0} has already added, you can't add new blendShape key on here!" },
                        { "apply_menu_find_tip", "Found “{0}” menu，do you want to use it as a tool main menu? This will replace the original content!" },
                        { "apply_success_tip", "Apply success!" },
                    }
                },
            };
        }
    }
}